# Generated by Django 4.2.3 on 2023-08-07 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Media/')),
                ('established_date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=100)),
                ('official_website', models.URLField()),
                ('school_motto', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
